#!/usr/bin/env bash
#This script is displaying Best school 9 times and hi on the last line

count=1
while [ $count -le 10 ]
do
    echo "Best School"
    if [ $count -eq 9 ]; then
        echo "Hi"
    fi
    ((count++))
done
