#!/usr/bin/env bash
# this script will display The content of the current directory in a list format where only the part of the name after the first dash is displayed
 
for file in *
do
    if [[ -f "$file" ]]; then
        new_name="${file#*-}"
        echo "$new_name"
    fi
done

