#!/usr/bin/env bash
#this sript is displaying text "to infinity and beyond" indefinitely with sleep 2 iteration and the Iam invicible!!! on a SIGTERM sign
#the loop that displays "To infinity and beyond"indefinitely
 while true; do

         echo "To infinity and beyond"
         sleep 2


       	 trap 'echo "I am invincible!!!"' SIGTERM   
 done
