#!/usr/bin/env bash
#this sript is displaying text "to infinity and beyond" indefinitely with sleep 2 iteration and the Iam invicible!!! on a SIGTERM signal
#let's use trap command since it listens for SIGTERM signal and executes the echo command
trap 'echo "Iam invincible";exit 0' SIGTERM 
#the loop that displays "To infinity and beyond"indefinitely
 while true; do

         echo "To infinity and beyond"
         sleep 2

 done
