#!/usr/bin/env bash
#this script display "Iam alive" infinitely
# Infinite loop writing "I am alive!" to /tmp/my_process every 2 seconds
while true; do
    echo "I am alive!" >> /tmp/my_process
    sleep 2
done

